"""Remnawave panel API client — thin REST wrapper with Meridian error handling.

Direct REST client using httpx. No dependency on third-party SDK — gives us
full control over error handling, retries, and the sync/async boundary.

All methods are synchronous. The panel runs behind nginx on a secret HTTPS
path, accessible directly from the deployer's machine (no SSH tunneling).
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger("meridian.api")


class RemnawaveError(Exception):
    """Raised when a Remnawave API call fails."""

    def __init__(self, msg: str, *, hint: str = "", hint_type: str = "system"):
        super().__init__(msg)
        self.hint = hint
        self.hint_type = hint_type


class RemnawaveNotFoundError(RemnawaveError):
    """Resource not found (404)."""


class RemnawaveAuthError(RemnawaveError):
    """Authentication or authorization failure (401/403)."""


class RemnawaveNetworkError(RemnawaveError):
    """Transport-level failure (connection refused, timeout)."""


# ---------------------------------------------------------------------------
# Response models — lightweight dataclasses, not Pydantic
# ---------------------------------------------------------------------------


@dataclass
class User:
    """A Remnawave user (= Meridian client)."""

    uuid: str = ""
    short_uuid: str = ""
    username: str = ""
    status: str = ""  # "ACTIVE", "DISABLED", "LIMITED", "EXPIRED"
    used_traffic_bytes: int = 0
    traffic_limit_bytes: int = 0
    created_at: str = ""
    online_at: str = ""
    sub_revoked_at: str = ""
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class Node:
    """A Remnawave proxy node."""

    uuid: str = ""
    name: str = ""
    address: str = ""
    port: int = 0
    is_connected: bool = False
    is_disabled: bool = False
    xray_version: str = ""
    traffic_used: int = 0
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class Host:
    """A Remnawave host entry (direct address or relay)."""

    uuid: str = ""
    remark: str = ""
    address: str = ""
    port: int = 0
    sni: str = ""
    inbound_uuid: str = ""
    is_disabled: bool = False
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class Inbound:
    """A Remnawave inbound (protocol definition)."""

    uuid: str = ""
    tag: str = ""
    type: str = ""  # "vless", "trojan", "shadowsocks"
    network: str = ""  # "tcp", "ws", "xhttp"
    security: str = ""  # "reality", "tls", "none"
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class ConfigProfile:
    """A Remnawave config profile (Xray configuration template)."""

    uuid: str = ""
    name: str = ""
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class NodeCredentials:
    """Connection credentials for a new node (generated by panel)."""

    uuid: str = ""
    secret_key: str = ""  # base64 JSON with mTLS certs
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


# ---------------------------------------------------------------------------
# API Client
# ---------------------------------------------------------------------------


class MeridianPanel:
    """Remnawave API client — sync REST with retries and Meridian error types.

    Usage:
        panel = MeridianPanel("https://panel.example.com", "jwt-token")
        user = panel.create_user("alice")
        nodes = panel.list_nodes()
    """

    def __init__(self, base_url: str, api_token: str, *, timeout: int = 30, max_retries: int = 3):
        import httpx

        self._base = base_url.rstrip("/")
        self._token = api_token
        self._timeout = timeout
        self._max_retries = max_retries
        self._client = httpx.Client(
            base_url=self._base,
            headers={
                "Authorization": f"Bearer {api_token}",
                "Content-Type": "application/json",
            },
            timeout=timeout,
            verify=False,  # Panel may use self-signed cert behind nginx
        )

    def close(self) -> None:
        """Close the underlying HTTP client."""
        self._client.close()

    def __enter__(self) -> MeridianPanel:
        return self

    def __exit__(self, *args: Any) -> None:
        self.close()

    # --- Low-level request ---

    def _request(self, method: str, path: str, *, json: Any = None, params: dict[str, Any] | None = None) -> Any:
        """Make an API request with retry logic."""
        import httpx

        logger.debug("%s %s", method, path)
        last_error: Exception | None = None
        for attempt in range(self._max_retries):
            try:
                resp = self._client.request(method, path, json=json, params=params)
                if resp.status_code == 401:
                    raise RemnawaveAuthError(
                        "Panel authentication failed (401)",
                        hint="Check your API token — it may have expired",
                        hint_type="user",
                    )
                if resp.status_code == 403:
                    raise RemnawaveAuthError(
                        "Panel access forbidden (403)",
                        hint="API token lacks required permissions",
                        hint_type="user",
                    )
                if resp.status_code == 404:
                    raise RemnawaveNotFoundError(
                        f"Resource not found: {path}",
                        hint_type="system",
                    )
                if resp.status_code >= 500:
                    last_error = RemnawaveError(f"Panel server error ({resp.status_code}): {resp.text[:200]}")
                    if attempt < self._max_retries - 1:
                        logger.debug("Retry %d/%d after %s", attempt + 1, self._max_retries, "ServerError")
                        time.sleep(2**attempt)
                        continue
                    raise last_error
                resp.raise_for_status()
                try:
                    data = resp.json()
                except (ValueError, Exception) as e:
                    raise RemnawaveError(
                        f"Panel returned invalid JSON ({len(resp.content)} bytes)",
                        hint=f"Response may be truncated by firewall or DPI: {e}",
                        hint_type="system",
                    ) from e
                logger.debug("← %s (%d bytes)", resp.status_code, len(resp.content))
                # Remnawave wraps responses in {"response": ...}
                if isinstance(data, dict) and "response" in data:
                    return data["response"]
                return data
            except httpx.ConnectError as e:
                last_error = RemnawaveNetworkError(
                    f"Cannot connect to panel at {self._base}",
                    hint=f"Is the panel running? Check: curl {self._base}/api/health\n{e}",
                    hint_type="system",
                )
                if attempt < self._max_retries - 1:
                    logger.debug("Retry %d/%d after %s", attempt + 1, self._max_retries, type(e).__name__)
                    time.sleep(2**attempt)
                    continue
            except httpx.TimeoutException as e:
                last_error = RemnawaveNetworkError(
                    f"Panel request timed out after {self._timeout}s",
                    hint=f"Panel may be overloaded or unreachable: {e}",
                    hint_type="system",
                )
                if attempt < self._max_retries - 1:
                    logger.debug("Retry %d/%d after %s", attempt + 1, self._max_retries, type(e).__name__)
                    time.sleep(2**attempt)
                    continue
            except httpx.HTTPStatusError as e:
                raise RemnawaveError(f"Panel API error: {e.response.status_code} {e.response.text[:200]}") from e

        if last_error:
            raise last_error
        raise RemnawaveError("Request failed after retries")

    def _get(self, path: str, **params: Any) -> Any:
        return self._request("GET", path, params=params if params else None)

    def _post(self, path: str, json: Any = None) -> Any:
        return self._request("POST", path, json=json)

    def _patch(self, path: str, json: Any = None) -> Any:
        return self._request("PATCH", path, json=json)

    def _delete(self, path: str) -> Any:
        return self._request("DELETE", path)

    # --- Health ---

    def ping(self) -> bool:
        """Check if the panel is reachable and authenticated."""
        try:
            self._get("/api/users", take=1, skip=0)
            return True
        except RemnawaveError:
            return False

    # --- Users (= Meridian clients) ---

    def create_user(self, username: str, *, traffic_limit_bytes: int = 0, expire_at: str = "") -> User:
        """Create a new user in Remnawave."""
        body: dict[str, Any] = {"username": username}
        if traffic_limit_bytes > 0:
            body["trafficLimitBytes"] = traffic_limit_bytes
        # Remnawave requires expireAt — use far future if not specified
        body["expireAt"] = expire_at or "2099-12-31T23:59:59.000Z"
        data = self._post("/api/users", json=body)
        return _parse_user(data)

    def get_user(self, username: str) -> User | None:
        """Find a user by username. Returns None only if not found (404)."""
        try:
            data = self._get(f"/api/users/by-username/{username}")
            return _parse_user(data)
        except RemnawaveNotFoundError:
            return None

    def get_user_by_uuid(self, uuid: str) -> User | None:
        """Find a user by UUID. Returns None only if not found (404)."""
        try:
            data = self._get(f"/api/users/{uuid}")
            return _parse_user(data)
        except RemnawaveNotFoundError:
            return None

    def list_users(self) -> list[User]:
        """List all users."""
        data = self._get("/api/users")
        if isinstance(data, list):
            return [_parse_user(u) for u in data]
        # Paginated response
        if isinstance(data, dict) and "users" in data:
            return [_parse_user(u) for u in data["users"]]
        return []

    def delete_user(self, uuid: str) -> bool:
        """Delete a user by UUID. Returns False only if not found."""
        try:
            self._delete(f"/api/users/{uuid}")
            return True
        except RemnawaveNotFoundError:
            return False

    def enable_user(self, uuid: str) -> None:
        """Enable a disabled user."""
        self._post(f"/api/users/enable/{uuid}")

    def disable_user(self, uuid: str) -> None:
        """Disable a user."""
        self._post(f"/api/users/disable/{uuid}")

    # --- Nodes ---

    def create_node(
        self,
        name: str,
        address: str,
        port: int,
        *,
        config_profile_uuid: str = "",
        inbound_uuids: list[str] | None = None,
        country_code: str = "XX",
    ) -> NodeCredentials:
        """Register a new node with the panel.

        Returns credentials including the SECRET_KEY for the node container.
        The secret key is fetched from the /api/keygen endpoint.
        """
        body: dict[str, Any] = {
            "name": name,
            "address": address,
            "port": port,
            "countryCode": country_code,
            "configProfile": {
                "activeConfigProfileUuid": config_profile_uuid,
                "activeInbounds": inbound_uuids or [],
            },
        }
        data = self._post("/api/nodes", json=body)
        node_uuid = data.get("uuid", "")

        # Fetch the connection string (mTLS cert bundle) from keygen
        keygen = self._get("/api/keygen")
        secret_key = ""
        if isinstance(keygen, dict):
            secret_key = keygen.get("pubKey", "")

        return NodeCredentials(
            uuid=node_uuid,
            secret_key=secret_key,
            _raw=data,
        )

    def list_nodes(self) -> list[Node]:
        """List all registered nodes."""
        data = self._get("/api/nodes")
        if isinstance(data, list):
            return [_parse_node(n) for n in data]
        return []

    def find_node_by_address(self, address: str) -> Node | None:
        """Find a node by its address. Returns None if not found."""
        for node in self.list_nodes():
            if node.address == address:
                return node
        return None

    def get_node(self, uuid: str) -> Node | None:
        """Get a node by UUID. Returns None only if not found (404)."""
        try:
            data = self._get(f"/api/nodes/{uuid}")
            return _parse_node(data)
        except RemnawaveNotFoundError:
            return None

    def enable_node(self, uuid: str) -> None:
        """Enable a disabled node."""
        self._post(f"/api/nodes/enable/{uuid}")

    def disable_node(self, uuid: str) -> None:
        """Disable a node."""
        self._post(f"/api/nodes/disable/{uuid}")

    def restart_node(self, uuid: str) -> None:
        """Restart Xray on a node."""
        self._post(f"/api/nodes/restart/{uuid}")

    def delete_node(self, uuid: str) -> None:
        """Deregister a node."""
        self._delete(f"/api/nodes/{uuid}")

    # --- Hosts (relays map here) ---

    def create_host(
        self,
        *,
        remark: str,
        address: str,
        port: int,
        config_profile_uuid: str,
        inbound_uuid: str,
        sni: str = "",
        host_header: str = "",
        path: str = "",
        alpn: str | None = None,
        fingerprint: str | None = None,
        security_layer: str = "DEFAULT",
        is_disabled: bool = False,
    ) -> Host:
        """Create a host entry (direct address or relay)."""
        body: dict[str, Any] = {
            "remark": remark,
            "address": address,
            "port": port,
            "inbound": {
                "configProfileUuid": config_profile_uuid,
                "configProfileInboundUuid": inbound_uuid,
            },
        }
        if sni:
            body["sni"] = sni
        if host_header:
            body["host"] = host_header
        if path:
            body["path"] = path
        if alpn is not None:
            body["alpn"] = alpn
        if fingerprint is not None:
            body["fingerprint"] = fingerprint
        if security_layer != "DEFAULT":
            body["securityLayer"] = security_layer
        if is_disabled:
            body["isDisabled"] = True
        data = self._post("/api/hosts", json=body)
        return _parse_host(data)

    def list_hosts(self) -> list[Host]:
        """List all host entries."""
        data = self._get("/api/hosts")
        if isinstance(data, list):
            return [_parse_host(h) for h in data]
        return []

    def find_host_by_remark(self, remark: str) -> Host | None:
        """Find a host by its remark string. Returns None if not found."""
        for host in self.list_hosts():
            if host.remark == remark:
                return host
        return None

    def enable_host(self, uuid: str) -> None:
        """Enable a disabled host."""
        self._post(f"/api/hosts/enable/{uuid}")

    def disable_host(self, uuid: str) -> None:
        """Disable a host (subscriptions auto-exclude)."""
        self._post(f"/api/hosts/disable/{uuid}")

    def delete_host(self, uuid: str) -> None:
        """Delete a host entry."""
        self._delete(f"/api/hosts/{uuid}")

    # --- Config Profiles ---

    def create_config_profile(self, name: str, config: dict[str, Any]) -> ConfigProfile:
        """Create a new config profile with Xray configuration."""
        body = {"name": name, "config": config}
        data = self._post("/api/config-profiles", json=body)
        return ConfigProfile(
            uuid=data.get("uuid", ""),
            name=data.get("name", ""),
            _raw=data,
        )

    def get_config_profile(self, uuid: str) -> ConfigProfile | None:
        """Get a config profile by UUID. Returns None only if not found (404)."""
        try:
            data = self._get(f"/api/config-profiles/{uuid}")
            return ConfigProfile(uuid=data.get("uuid", ""), name=data.get("name", ""), _raw=data)
        except RemnawaveNotFoundError:
            return None

    def list_config_profiles(self) -> list[ConfigProfile]:
        """List all config profiles."""
        data = self._get("/api/config-profiles")
        if isinstance(data, list):
            return [ConfigProfile(uuid=p.get("uuid", ""), name=p.get("name", ""), _raw=p) for p in data]
        return []

    def find_config_profile_by_name(self, name: str) -> ConfigProfile | None:
        """Find a config profile by name. Returns None if not found."""
        for profile in self.list_config_profiles():
            if profile.name == name:
                return profile
        return None

    # --- Inbounds ---

    def list_inbounds(self) -> list[Inbound]:
        """List all inbounds across config profiles."""
        data = self._get("/api/config-profiles/inbounds")
        if isinstance(data, dict) and "inbounds" in data:
            return [_parse_inbound(ib) for ib in data["inbounds"]]
        if isinstance(data, list):
            return [_parse_inbound(ib) for ib in data]
        return []

    # --- Subscriptions ---

    def get_subscription_url(self, short_uuid: str) -> str:
        """Build the subscription URL for a user."""
        return f"{self._base}/api/sub/{short_uuid}"

    # --- Xray Config ---

    def get_xray_config(self) -> dict[str, Any]:
        """Get the global Xray configuration (DNS, routing, etc.)."""
        data = self._get("/api/xray/config")
        if isinstance(data, dict):
            return data
        return {}

    def update_xray_config(self, config: dict[str, Any]) -> None:
        """Update the global Xray configuration."""
        self._patch("/api/xray/config", json=config)

    # --- Auth (for initial setup) ---

    @classmethod
    def login(cls, base_url: str, username: str, password: str, *, timeout: int = 30) -> str:
        """Authenticate and return an API token.

        Used during initial panel setup when we don't have a token yet.
        """
        import httpx

        resp = httpx.post(
            f"{base_url.rstrip('/')}/api/auth/login",
            json={"username": username, "password": password},
            timeout=timeout,
            verify=False,
        )
        if resp.status_code != 200:
            raise RemnawaveError(
                f"Panel login failed ({resp.status_code})",
                hint="Check panel credentials",
                hint_type="user",
            )
        data = resp.json()
        if isinstance(data, dict) and "response" in data:
            data = data["response"]
        token = data.get("accessToken", "") or data.get("token", "")
        if not token:
            raise RemnawaveError("Login succeeded but no token returned", hint_type="bug")
        return token

    @classmethod
    def register_admin(cls, base_url: str, username: str, password: str, *, timeout: int = 30) -> str:
        """Register the initial admin user during setup.

        Returns an API token.
        """
        import httpx

        resp = httpx.post(
            f"{base_url.rstrip('/')}/api/auth/register",
            json={"username": username, "password": password},
            timeout=timeout,
            verify=False,
        )
        if resp.status_code not in (200, 201):
            raise RemnawaveError(
                f"Admin registration failed ({resp.status_code}): {resp.text[:200]}",
                hint_type="system",
            )
        data = resp.json()
        if isinstance(data, dict) and "response" in data:
            data = data["response"]
        token = data.get("accessToken", "") or data.get("token", "")
        if not token:
            raise RemnawaveError("Registration succeeded but no token returned", hint_type="bug")
        return token


# ---------------------------------------------------------------------------
# Response parsers
# ---------------------------------------------------------------------------


def _parse_user(data: Any) -> User:
    if not isinstance(data, dict):
        return User()
    return User(
        uuid=data.get("uuid", ""),
        short_uuid=data.get("shortUuid", "") or data.get("short_uuid", ""),
        username=data.get("username", ""),
        status=data.get("status", ""),
        used_traffic_bytes=data.get("usedTrafficBytes", 0) or 0,
        traffic_limit_bytes=data.get("trafficLimitBytes", 0) or 0,
        created_at=data.get("createdAt", ""),
        online_at=data.get("onlineAt", "") or data.get("lastOnline", ""),
        sub_revoked_at=data.get("subRevokedAt", ""),
        _raw=data,
    )


def _parse_node(data: Any) -> Node:
    if not isinstance(data, dict):
        return Node()
    return Node(
        uuid=data.get("uuid", ""),
        name=data.get("name", ""),
        address=data.get("address", ""),
        port=data.get("port", 0),
        is_connected=data.get("isConnected", False),
        is_disabled=data.get("isDisabled", False),
        xray_version=data.get("xrayVersion", ""),
        traffic_used=data.get("trafficUsed", 0) or 0,
        _raw=data,
    )


def _parse_host(data: Any) -> Host:
    if not isinstance(data, dict):
        return Host()
    return Host(
        uuid=data.get("uuid", ""),
        remark=data.get("remark", ""),
        address=data.get("address", ""),
        port=data.get("port", 0),
        sni=data.get("sni", ""),
        inbound_uuid=data.get("inboundUuid", "") or data.get("inbound_uuid", ""),
        is_disabled=data.get("isDisabled", False),
        _raw=data,
    )


def _parse_inbound(data: Any) -> Inbound:
    if not isinstance(data, dict):
        return Inbound()
    return Inbound(
        uuid=data.get("uuid", ""),
        tag=data.get("tag", ""),
        type=data.get("type", ""),
        network=data.get("network", ""),
        security=data.get("security", ""),
        _raw=data,
    )
