"""Remnawave panel API client — sync facade over the official SDK.

Uses the official ``remnawave`` SDK for panel operations and falls back
to raw ``httpx`` only for auth helpers and generic escape hatches.

All methods are synchronous — async SDK calls are bridged via
``asyncio.run()``. The panel runs behind nginx on a secret HTTPS path,
accessible directly from the deployer's machine (no SSH tunneling).
"""

from __future__ import annotations

import asyncio
import logging
import random
import time
from dataclasses import dataclass, field
from typing import Any
from uuid import UUID

from remnawave import RemnawaveSDK
from remnawave.exceptions import ApiError, ForbiddenError, NetworkError, NotFoundError, UnauthorizedError
from remnawave.models.config_profiles import CreateConfigProfileRequestDto
from remnawave.models.hosts import CreateHostInboundData, CreateHostRequestDto
from remnawave.models.internal_squads import UpdateInternalSquadRequestDto
from remnawave.models.nodes import CreateNodeRequestDto, NodeConfigProfileRequestDto
from remnawave.models.users import CreateUserRequestDto

logger = logging.getLogger("meridian.api")


class RemnawaveError(Exception):
    """Raised when a Remnawave API call fails."""

    def __init__(self, msg: str, *, hint: str = "", hint_type: str = "system"):
        super().__init__(msg)
        self.hint = hint
        self.hint_type = hint_type


class RemnawaveNotFoundError(RemnawaveError):
    """Resource not found (404)."""


class RemnawaveAuthError(RemnawaveError):
    """Authentication or authorization failure (401/403)."""


class RemnawaveNetworkError(RemnawaveError):
    """Transport-level failure (connection refused, timeout)."""


# ---------------------------------------------------------------------------
# Response models — lightweight dataclasses kept for backward compatibility
# ---------------------------------------------------------------------------


@dataclass
class User:
    """A Remnawave user (= Meridian client)."""

    uuid: str = ""
    short_uuid: str = ""
    username: str = ""
    vless_uuid: str = ""  # VLESS protocol UUID (used by Xray, differs from account UUID)
    status: str = ""  # "ACTIVE", "DISABLED", "LIMITED", "EXPIRED"
    used_traffic_bytes: int = 0
    traffic_limit_bytes: int = 0
    created_at: str = ""
    online_at: str = ""
    sub_revoked_at: str = ""
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class Node:
    """A Remnawave proxy node."""

    uuid: str = ""
    name: str = ""
    address: str = ""
    port: int = 0
    is_connected: bool = False
    is_disabled: bool = False
    xray_version: str = ""
    traffic_used: int = 0
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class Host:
    """A Remnawave host entry (direct address or relay)."""

    uuid: str = ""
    remark: str = ""
    address: str = ""
    port: int = 0
    sni: str = ""
    inbound_uuid: str = ""
    is_disabled: bool = False
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class Inbound:
    """A Remnawave inbound (protocol definition)."""

    uuid: str = ""
    tag: str = ""
    type: str = ""  # "vless", "trojan", "shadowsocks"
    network: str = ""  # "tcp", "ws", "xhttp"
    security: str = ""  # "reality", "tls", "none"
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class ConfigProfile:
    """A Remnawave config profile (Xray configuration template)."""

    uuid: str = ""
    name: str = ""
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


@dataclass
class NodeCredentials:
    """Connection credentials for a new node (generated by panel)."""

    uuid: str = ""
    secret_key: str = ""  # base64 JSON with mTLS certs
    _raw: dict[str, Any] = field(default_factory=dict, repr=False)


# ---------------------------------------------------------------------------
# SDK ↔ dataclass converters
# ---------------------------------------------------------------------------


def _user_from_sdk(obj: Any) -> User:
    """Convert SDK UserResponseDto to our User dataclass."""
    traffic = getattr(obj, "userTraffic", None)
    return User(
        uuid=str(getattr(obj, "uuid", "")),
        short_uuid=str(getattr(obj, "shortUuid", "") or getattr(obj, "short_uuid", "")),
        username=getattr(obj, "username", ""),
        vless_uuid=str(getattr(obj, "vlessUuid", "") or getattr(obj, "vless_uuid", "")),
        status=str(getattr(obj, "status", "") or ""),
        used_traffic_bytes=int(getattr(obj, "usedTrafficBytes", None) or getattr(traffic, "usedTrafficBytes", 0) or 0),
        traffic_limit_bytes=int(getattr(obj, "trafficLimitBytes", 0) or 0),
        created_at=str(getattr(obj, "createdAt", "") or ""),
        online_at=str(getattr(obj, "onlineAt", None) or getattr(traffic, "onlineAt", "") or ""),
        sub_revoked_at=str(getattr(obj, "subRevokedAt", "") or ""),
    )


def _node_from_sdk(obj: Any) -> Node:
    """Convert SDK NodeResponseDto to our Node dataclass."""
    return Node(
        uuid=str(getattr(obj, "uuid", "")),
        name=getattr(obj, "name", ""),
        address=getattr(obj, "address", ""),
        port=int(getattr(obj, "port", 0) or 0),
        is_connected=bool(getattr(obj, "isConnected", False)),
        is_disabled=bool(getattr(obj, "isDisabled", False)),
        xray_version=getattr(obj, "xrayVersion", "") or "",
        traffic_used=int(getattr(obj, "trafficUsedBytes", 0) or 0),
    )


def _host_from_sdk(obj: Any) -> Host:
    """Convert SDK HostResponseDto to our Host dataclass."""
    inbound = getattr(obj, "inbound", None)
    return Host(
        uuid=str(getattr(obj, "uuid", "")),
        remark=getattr(obj, "remark", ""),
        address=getattr(obj, "address", ""),
        port=int(getattr(obj, "port", 0) or 0),
        sni=getattr(obj, "sni", "") or "",
        inbound_uuid=str(getattr(obj, "inboundUuid", "") or getattr(inbound, "configProfileInboundUuid", "") or ""),
        is_disabled=bool(getattr(obj, "isDisabled", False)),
    )


def _inbound_from_sdk(obj: Any) -> Inbound:
    """Convert SDK inbound DTO to our Inbound dataclass."""
    return Inbound(
        uuid=str(getattr(obj, "uuid", "")),
        tag=getattr(obj, "tag", ""),
        type=getattr(obj, "type", ""),
        network=getattr(obj, "network", "") or "",
        security=getattr(obj, "security", "") or "",
    )


def _config_profile_from_sdk(obj: Any) -> ConfigProfile:
    """Convert SDK ConfigProfileDto to our ConfigProfile dataclass."""
    return ConfigProfile(
        uuid=str(getattr(obj, "uuid", "")),
        name=getattr(obj, "name", ""),
        _raw=_sdk_to_dict(obj) if obj is not None else {},
    )


def _sdk_items(resp: Any, *, attr: str | None = None) -> list[Any]:
    """Extract list payloads from SDK responses with mixed shapes."""
    if resp is None:
        return []
    if attr:
        items = getattr(resp, attr, None)
        if isinstance(items, list):
            return items
    root = getattr(resp, "root", None)
    if isinstance(root, list):
        return root
    if isinstance(resp, list):
        return resp
    return []


def _sdk_to_dict(obj: Any) -> Any:
    """Recursively convert SDK models to plain Python containers."""
    if hasattr(obj, "model_dump"):
        return obj.model_dump(mode="python")
    if isinstance(obj, list):
        return [_sdk_to_dict(item) for item in obj]
    if isinstance(obj, tuple):
        return [_sdk_to_dict(item) for item in obj]
    if isinstance(obj, dict):
        return {key: _sdk_to_dict(value) for key, value in obj.items()}
    return obj


# ---------------------------------------------------------------------------
# Async → sync bridge
# ---------------------------------------------------------------------------


def _run(coro: Any) -> Any:
    """Run an async coroutine synchronously."""
    return asyncio.run(coro)


# ---------------------------------------------------------------------------
# SDK error → Meridian error mapping
# ---------------------------------------------------------------------------


def _sdk_call(coro: Any) -> Any:
    """Run an async SDK coroutine, converting SDK exceptions to Meridian types.

    All SDK-backed methods should use this instead of bare ``_run()``.
    """
    try:
        return _run(coro)
    except (RemnawaveError, RemnawaveNotFoundError, RemnawaveAuthError, RemnawaveNetworkError):
        raise
    except NetworkError as e:
        raise RemnawaveNetworkError(f"Panel network error: {e}", hint_type="system") from e
    except Exception as e:
        if isinstance(e, NotFoundError):
            raise RemnawaveNotFoundError(f"Resource not found: {e}", hint_type="system") from e
        if isinstance(e, (UnauthorizedError, ForbiddenError)):
            raise RemnawaveAuthError(
                f"Panel authentication failed: {e}",
                hint="Check your API token — it may have expired",
                hint_type="user",
            ) from e
        if isinstance(e, ApiError):
            raise RemnawaveError(f"Panel API error: {e}", hint_type="system") from e
        raise


# ---------------------------------------------------------------------------
# API Client
# ---------------------------------------------------------------------------


class MeridianPanel:
    """Remnawave API client — sync facade over the official SDK.

    Uses the official ``remnawave`` SDK for panel operations and falls
    back to raw httpx only for auth helpers and generic low-level access.

    Usage:
        panel = MeridianPanel("https://panel.example.com", "jwt-token")
        user = panel.create_user("alice")
        nodes = panel.list_nodes()
    """

    def __init__(self, base_url: str, api_token: str, *, timeout: int = 30, max_retries: int = 5):
        import httpx

        self._base = base_url.rstrip("/")
        self._token = api_token
        self._timeout = timeout
        self._max_retries = max_retries

        # SDK client for supported endpoints
        self._sdk = RemnawaveSDK(base_url=self._base, token=api_token)

        # Raw httpx client for endpoints the SDK doesn't cover
        self._client = httpx.Client(
            base_url=self._base + "/",
            headers={
                "Authorization": f"Bearer {api_token}",
                "Content-Type": "application/json",
            },
            timeout=timeout,
            verify=False,
        )

    def close(self) -> None:
        """Close the underlying HTTP clients."""
        self._client.close()

    def __enter__(self) -> MeridianPanel:
        return self

    def __exit__(self, *args: Any) -> None:
        self.close()

    # --- Low-level raw request (for endpoints not in SDK) ---

    def _request(self, method: str, path: str, *, json: Any = None, params: dict[str, Any] | None = None) -> Any:
        """Make a raw API request with retry logic (for SDK gaps)."""
        import httpx

        path = path.lstrip("/")
        logger.debug("%s %s", method, path)
        last_error: Exception | None = None
        for attempt in range(self._max_retries):
            try:
                resp = self._client.request(method, path, json=json, params=params)
                if resp.status_code == 401:
                    raise RemnawaveAuthError(
                        "Panel authentication failed (401)",
                        hint="Check your API token — it may have expired",
                        hint_type="user",
                    )
                if resp.status_code == 403:
                    raise RemnawaveAuthError(
                        "Panel access forbidden (403)",
                        hint="API token lacks required permissions",
                        hint_type="user",
                    )
                if resp.status_code == 404:
                    raise RemnawaveNotFoundError(f"Resource not found: {path}", hint_type="system")
                if resp.status_code >= 500:
                    last_error = RemnawaveError(f"Panel server error ({resp.status_code}): {resp.text[:200]}")
                    if attempt < self._max_retries - 1:
                        time.sleep(min(2**attempt, 16) + random.uniform(0, 1))
                        continue
                    raise last_error
                resp.raise_for_status()
                try:
                    data = resp.json()
                except Exception as e:
                    raise RemnawaveError(
                        f"Panel returned invalid JSON ({len(resp.content)} bytes)",
                        hint=f"Response may be truncated by firewall or DPI: {e}",
                        hint_type="system",
                    ) from e
                if isinstance(data, dict) and "response" in data:
                    return data["response"]
                return data
            except httpx.ConnectError as e:
                last_error = RemnawaveNetworkError(
                    f"Cannot connect to panel at {self._base}",
                    hint=f"Is the panel running? Check: curl {self._base}/api/health\n{e}",
                    hint_type="system",
                )
                if attempt < self._max_retries - 1:
                    time.sleep(2**attempt)
                    continue
            except httpx.TimeoutException as e:
                last_error = RemnawaveNetworkError(
                    f"Panel request timed out after {self._timeout}s",
                    hint=f"Panel may be overloaded or unreachable: {e}",
                    hint_type="system",
                )
                if attempt < self._max_retries - 1:
                    time.sleep(2**attempt)
                    continue
            except httpx.HTTPStatusError as e:
                raise RemnawaveError(f"Panel API error: {e.response.status_code} {e.response.text[:200]}") from e

        if last_error:
            raise last_error
        raise RemnawaveError("Request failed after retries")

    def _get(self, path: str, **params: Any) -> Any:
        return self._request("GET", path, params=params if params else None)

    def _post(self, path: str, json: Any = None) -> Any:
        return self._request("POST", path, json=json)

    def _patch(self, path: str, json: Any = None) -> Any:
        return self._request("PATCH", path, json=json)

    def _delete(self, path: str) -> Any:
        return self._request("DELETE", path)

    # --- Health ---

    def ping(self) -> bool:
        """Check if the panel is reachable and authenticated."""
        try:
            _sdk_call(self._sdk.users.get_all_users(start=0, size=1))
            return True
        except Exception:
            return False

    # --- Users (= Meridian clients) ---

    def create_user(
        self,
        username: str,
        *,
        traffic_limit_bytes: int = 0,
        expire_at: str = "",
        squad_uuids: list[str] | None = None,
    ) -> User:
        """Create a new user in Remnawave.

        SDK v2 supports ``active_internal_squads`` directly.
        """
        body = CreateUserRequestDto(
            username=username,
            expire_at=expire_at or "2099-12-31T23:59:59.000Z",
            traffic_limit_bytes=traffic_limit_bytes if traffic_limit_bytes > 0 else None,
            active_internal_squads=squad_uuids or None,
        )
        resp = _sdk_call(self._sdk.users.create_user(body))
        return _user_from_sdk(resp)

    def get_user(self, username: str) -> User | None:
        """Find a user by username. Returns None only if not found (404)."""
        try:
            resp = _sdk_call(self._sdk.users.get_user_by_username(username))
            return _user_from_sdk(resp)
        except RemnawaveNotFoundError:
            return None

    def get_user_by_uuid(self, uuid: str) -> User | None:
        """Find a user by UUID. Returns None only if not found (404)."""
        try:
            resp = _sdk_call(self._sdk.users.get_user_by_uuid(uuid))
            return _user_from_sdk(resp)
        except RemnawaveNotFoundError:
            return None

    def list_users(self) -> list[User]:
        """List all users."""
        resp = _sdk_call(self._sdk.users.get_all_users(start=0, size=10000))
        users_list = getattr(resp, "users", []) or []
        return [_user_from_sdk(u) for u in users_list]

    def delete_user(self, uuid: str) -> bool:
        """Delete a user by UUID. Returns False only if not found."""
        try:
            _sdk_call(self._sdk.users.delete_user(uuid))
            return True
        except RemnawaveNotFoundError:
            return False

    def enable_user(self, uuid: str) -> None:
        """Enable a disabled user."""
        _sdk_call(self._sdk.users.enable_user(uuid))

    def disable_user(self, uuid: str) -> None:
        """Disable a user."""
        _sdk_call(self._sdk.users.disable_user(uuid))

    # --- Nodes ---

    def create_node(
        self,
        name: str,
        address: str,
        port: int,
        *,
        config_profile_uuid: str = "",
        inbound_uuids: list[str] | None = None,
        country_code: str = "XX",
    ) -> NodeCredentials:
        """Register a new node with the panel.

        Returns credentials including the SECRET_KEY for the node container.
        """
        if config_profile_uuid:
            body = CreateNodeRequestDto(
                name=name,
                address=address,
                port=port,
                country_code=country_code,
                config_profile=NodeConfigProfileRequestDto(
                    activeConfigProfileUuid=config_profile_uuid,
                    activeInbounds=inbound_uuids or [],
                ),
            )
            resp = _sdk_call(self._sdk.nodes.create_node(body))
            data = _sdk_to_dict(resp)
            node_uuid = str(getattr(resp, "uuid", ""))
        else:
            # Keep a raw fallback for compatibility with callers that do not
            # yet provide a config profile binding.
            body = {
                "name": name,
                "address": address,
                "port": port,
                "countryCode": country_code,
                "configProfile": {
                    "activeConfigProfileUuid": config_profile_uuid,
                    "activeInbounds": inbound_uuids or [],
                },
            }
            data = self._post("/api/nodes", json=body)
            node_uuid = data.get("uuid", "")

        return NodeCredentials(uuid=node_uuid, secret_key=self.get_node_secret_key(), _raw=data)

    def list_nodes(self) -> list[Node]:
        """List all registered nodes."""
        resp = _sdk_call(self._sdk.nodes.get_all_nodes())
        nodes_list = _sdk_items(resp)
        return [_node_from_sdk(n) for n in nodes_list]

    def find_node_by_address(self, address: str) -> Node | None:
        """Find a node by its address. Returns None if not found."""
        for node in self.list_nodes():
            if node.address == address:
                return node
        return None

    def get_node(self, uuid: str) -> Node | None:
        """Get a node by UUID. Returns None only if not found (404)."""
        try:
            resp = _sdk_call(self._sdk.nodes.get_one_node(uuid))
            return _node_from_sdk(resp)
        except RemnawaveNotFoundError:
            return None

    def enable_node(self, uuid: str) -> None:
        """Enable a disabled node."""
        _sdk_call(self._sdk.nodes.enable_node(uuid))

    def disable_node(self, uuid: str) -> None:
        """Disable a node."""
        _sdk_call(self._sdk.nodes.disable_node(uuid))

    def restart_node(self, uuid: str) -> None:
        """Restart Xray on a node."""
        _sdk_call(self._sdk.nodes.restart_node(uuid))

    def delete_node(self, uuid: str) -> None:
        """Deregister a node."""
        _sdk_call(self._sdk.nodes.delete_node(uuid))

    def update_node_name(self, uuid: str, name: str) -> None:
        """Update a node's name in the panel."""
        from remnawave.models.nodes import UpdateNodeRequestDto

        body = UpdateNodeRequestDto(uuid=UUID(uuid), name=name)
        _sdk_call(self._sdk.nodes.update_node(body))

    # --- Hosts (relays map here) ---

    def create_host(
        self,
        *,
        remark: str,
        address: str,
        port: int,
        config_profile_uuid: str,
        inbound_uuid: str,
        sni: str = "",
        host_header: str = "",
        path: str = "",
        alpn: str | None = None,
        fingerprint: str | None = None,
        security_layer: str = "DEFAULT",
        is_disabled: bool = False,
    ) -> Host:
        """Create a host entry (direct address or relay).

        SDK v2 supports the nested inbound payload directly.
        """
        body = CreateHostRequestDto(
            remark=remark,
            address=address,
            port=port,
            inbound=CreateHostInboundData(
                config_profile_uuid=config_profile_uuid,
                config_profile_inbound_uuid=inbound_uuid,
            ),
            sni=sni or None,
            host=host_header or None,
            path=path or None,
            alpn=alpn,
            fingerprint=fingerprint,
            security_layer=security_layer,
            is_disabled=is_disabled,
        )
        resp = _sdk_call(self._sdk.hosts.create_host(body))
        return _host_from_sdk(resp)

    def list_hosts(self) -> list[Host]:
        """List all host entries."""
        resp = _sdk_call(self._sdk.hosts.get_all_hosts())
        hosts_list = _sdk_items(resp)
        return [_host_from_sdk(h) for h in hosts_list]

    def find_host_by_remark(self, remark: str) -> Host | None:
        """Find a host by its remark string. Returns None if not found."""
        for host in self.list_hosts():
            if host.remark == remark:
                return host
        return None

    def enable_host(self, uuid: str) -> None:
        """Enable a disabled host."""
        _sdk_call(self._sdk.hosts_bulk_actions.enable_hosts([UUID(uuid)]))

    def disable_host(self, uuid: str) -> None:
        """Disable a host (subscriptions auto-exclude)."""
        _sdk_call(self._sdk.hosts_bulk_actions.disable_hosts([UUID(uuid)]))

    def delete_host(self, uuid: str) -> None:
        """Delete a host entry."""
        _sdk_call(self._sdk.hosts.delete_host(uuid))

    # --- Config Profiles (not in SDK — raw httpx) ---
    # --- Config Profiles ---

    def create_config_profile(self, name: str, config: dict[str, Any]) -> ConfigProfile:
        """Create a new config profile with Xray configuration."""
        body = CreateConfigProfileRequestDto(name=name, config=config)
        resp = _sdk_call(self._sdk.config_profiles.create_config_profile(body))
        return _config_profile_from_sdk(resp)

    def get_config_profile(self, uuid: str) -> ConfigProfile | None:
        """Get a config profile by UUID. Returns None only if not found."""
        try:
            resp = _sdk_call(self._sdk.config_profiles.get_config_profile_by_uuid(uuid))
            return _config_profile_from_sdk(resp)
        except RemnawaveNotFoundError:
            return None

    def list_config_profiles(self) -> list[ConfigProfile]:
        """List all config profiles."""
        resp = _sdk_call(self._sdk.config_profiles.get_config_profiles())
        items = getattr(resp, "configProfiles", []) or []
        return [_config_profile_from_sdk(profile) for profile in items]

    def find_config_profile_by_name(self, name: str) -> ConfigProfile | None:
        """Find a config profile by name. Returns None if not found."""
        for profile in self.list_config_profiles():
            if profile.name == name:
                return profile
        return None

    # --- Inbounds ---

    def list_inbounds(self) -> list[Inbound]:
        """List all inbounds across config profiles."""
        resp = _sdk_call(self._sdk.inbounds.get_all_inbounds())
        inbounds_list = getattr(resp, "inbounds", []) or []
        return [_inbound_from_sdk(ib) for ib in inbounds_list]

    # --- Internal Squads ---

    def list_internal_squads(self) -> list[dict[str, Any]]:
        """List internal squads. Returns raw dicts with uuid, name, info."""
        resp = _sdk_call(self._sdk.internal_squads.get_internal_squads())
        return [_sdk_to_dict(squad) for squad in getattr(resp, "internalSquads", []) or []]

    def get_default_squad_uuid(self) -> str:
        """Get the UUID of the Default-Squad. Returns empty string if not found."""
        squads = self.list_internal_squads()
        for s in squads:
            if isinstance(s, dict) and s.get("name") == "Default-Squad":
                return s.get("uuid", "")
        return ""

    def assign_inbounds_to_squad(self, squad_uuid: str, inbound_uuids: list[str]) -> None:
        """Assign inbounds to an internal squad (PATCH)."""
        body = UpdateInternalSquadRequestDto(uuid=UUID(squad_uuid), inbounds=[UUID(uuid) for uuid in inbound_uuids])
        _sdk_call(self._sdk.internal_squads.update_internal_squad(body))

    # --- Keygen ---

    def get_node_secret_key(self) -> str:
        """Fetch the node mTLS secret bundle from the keygen controller."""
        resp = _sdk_call(self._sdk.keygen.generate_key())
        return str(getattr(resp, "pubKey", "") or "")

    # --- Subscriptions ---

    def get_subscription_url(self, short_uuid: str) -> str:
        """Build the subscription URL for a user."""
        return f"{self._base}/api/sub/{short_uuid}"

    # --- Xray Config ---

    def get_xray_config(self) -> dict[str, Any]:
        """Get the global Xray configuration (DNS, routing, etc.)."""
        data = self._get("/api/xray/config")
        if isinstance(data, dict):
            return data
        return {}

    def update_xray_config(self, config: dict[str, Any]) -> None:
        """Update the global Xray configuration."""
        self._patch("/api/xray/config", json=config)

    # --- Auth (for initial setup — raw httpx, no SDK instance yet) ---

    @classmethod
    def login(cls, base_url: str, username: str, password: str, *, timeout: int = 30) -> str:
        """Authenticate and return an auth token."""
        import httpx

        try:
            resp = httpx.post(
                f"{base_url.rstrip('/')}/api/auth/login",
                json={"username": username, "password": password},
                timeout=timeout,
                verify=False,
            )
        except httpx.ConnectError as e:
            raise RemnawaveNetworkError(
                f"Cannot connect to panel at {base_url}",
                hint=f"Is the panel running? {e}",
                hint_type="system",
            ) from e
        except httpx.TimeoutException:
            raise RemnawaveNetworkError(
                f"Panel login timed out after {timeout}s",
                hint_type="system",
            )
        if resp.status_code != 200:
            raise RemnawaveError(
                f"Panel login failed ({resp.status_code})",
                hint="Check panel credentials",
                hint_type="user",
            )
        try:
            data = resp.json()
        except (ValueError, TypeError) as e:
            raise RemnawaveError("Panel returned invalid JSON during login", hint_type="system") from e
        if isinstance(data, dict) and "response" in data:
            data = data["response"]
        token = data.get("accessToken", "") or data.get("token", "")
        if not token:
            raise RemnawaveError("Login succeeded but no token returned", hint_type="bug")
        return token

    @classmethod
    def register_admin(cls, base_url: str, username: str, password: str, *, timeout: int = 30) -> str:
        """Register the initial admin user during setup."""
        import httpx

        try:
            resp = httpx.post(
                f"{base_url.rstrip('/')}/api/auth/register",
                json={"username": username, "password": password},
                timeout=timeout,
                verify=False,
            )
        except httpx.ConnectError as e:
            raise RemnawaveNetworkError(
                f"Cannot connect to panel at {base_url}",
                hint=f"Is the panel running? {e}",
                hint_type="system",
            ) from e
        except httpx.TimeoutException:
            raise RemnawaveNetworkError(
                f"Panel registration timed out after {timeout}s",
                hint_type="system",
            )
        if resp.status_code not in (200, 201):
            raise RemnawaveError(
                f"Admin registration failed ({resp.status_code}): {resp.text[:200]}",
                hint_type="system",
            )
        try:
            data = resp.json()
        except (ValueError, TypeError) as e:
            raise RemnawaveError("Panel returned invalid JSON during registration", hint_type="system") from e
        if isinstance(data, dict) and "response" in data:
            data = data["response"]
        token = data.get("accessToken", "") or data.get("token", "")
        if not token:
            raise RemnawaveError("Registration succeeded but no token returned", hint_type="bug")
        return token


# ---------------------------------------------------------------------------
# Raw JSON → dataclass parsers (for endpoints using raw httpx)
# ---------------------------------------------------------------------------


def _parse_user(data: Any) -> User:
    if not isinstance(data, dict):
        return User()
    return User(
        uuid=data.get("uuid", ""),
        short_uuid=data.get("shortUuid", "") or data.get("short_uuid", ""),
        username=data.get("username", ""),
        vless_uuid=data.get("vlessUuid", "") or data.get("vless_uuid", ""),
        status=data.get("status", ""),
        used_traffic_bytes=data.get("usedTrafficBytes", 0) or 0,
        traffic_limit_bytes=data.get("trafficLimitBytes", 0) or 0,
        created_at=data.get("createdAt", ""),
        online_at=data.get("onlineAt", "") or data.get("lastOnline", ""),
        sub_revoked_at=data.get("subRevokedAt", ""),
        _raw=data,
    )


def _parse_host(data: Any) -> Host:
    if not isinstance(data, dict):
        return Host()
    return Host(
        uuid=data.get("uuid", ""),
        remark=data.get("remark", ""),
        address=data.get("address", ""),
        port=data.get("port", 0),
        sni=data.get("sni", ""),
        inbound_uuid=data.get("inboundUuid", "") or data.get("inbound_uuid", ""),
        is_disabled=data.get("isDisabled", False),
        _raw=data,
    )
