"""Meridian core API primitives.

Core modules expose typed request/result/event contracts used by CLI, future
UI clients, and automation adapters. They must not depend on Typer command
parsing or Rich console state.
"""

from meridian.core.apply import ApplyActionResult, ApplyCounts, ApplyResult, build_apply_result
from meridian.core.clients import (
    ClientDetail,
    ClientHandoff,
    ClientListResult,
    ClientListSummary,
    ClientRecord,
    ClientShowResult,
)
from meridian.core.deploy import (
    DeployRequest,
    DeployResult,
    DeployWorkflowAnswers,
    apply_deploy_workflow_answers,
    build_deploy_workflow,
)
from meridian.core.deploy_planning import (
    DeployClusterState,
    DeployNodeState,
    DeployPlan,
    DeployPlanningError,
    DeployPorts,
    build_deploy_plan,
    compute_deploy_ports,
)
from meridian.core.events import (
    COMMAND_COMPLETED,
    COMMAND_FAILED,
    COMMAND_STARTED,
    PROVISION_STEP_COMPLETED,
    PROVISION_STEP_FAILED,
    PROVISION_STEP_STARTED,
    CoreEventType,
)
from meridian.core.execution import (
    CommandSpec,
    PutBytesSpec,
    PutTextSpec,
    RemoteCommandResult,
    RemoteExecutor,
    RemoteTarget,
)
from meridian.core.fleet import FleetInventory, FleetSources, FleetStatus, FleetTopology, RelayHostRef
from meridian.core.models import (
    CoreModel,
    ErrorCategory,
    Event,
    EventLevel,
    MeridianError,
    OutputEnvelope,
    OutputStatus,
    ResourceRef,
    Summary,
)
from meridian.core.output import (
    EventStream,
    OperationContext,
    command_envelope,
    envelope,
    json_dumps,
    jsonl_dumps,
    plan_payload,
)
from meridian.core.plan import PlanActionResult, PlanCounts, PlanResult, build_plan_result
from meridian.core.redaction import REDACTED, redact
from meridian.core.reporters import CaptureReporter, NoopReporter, Reporter, emit_event
from meridian.core.schema import (
    ApiCommandsResult,
    ApiSchemaResult,
    ApiSchemasResult,
    ApiWorkflowResult,
    CommandCatalogEntry,
    CommandContract,
    CommandOutcome,
    EmptyData,
    SchemaCatalogEntry,
    command_catalog,
    command_contracts,
    schema_catalog,
    schema_for,
    schema_names,
    validate_command_envelope,
)
from meridian.core.services import (
    ClientListServiceResult,
    ClientNotFoundError,
    ClientPanelClient,
    ClientShowServiceResult,
    DeployExecutor,
    FleetInventoryServiceResult,
    FleetPanelClient,
    FleetStatusServiceResult,
    PanelErrorClassifier,
    PanelErrorKind,
    RelayHealthChecker,
    ShareUrlBuilder,
    WorkflowNotFoundError,
    collect_client_list,
    collect_client_show,
    collect_fleet_inventory,
    collect_fleet_status,
    collect_workflow,
    deploy_server,
)
from meridian.core.workflow import InputField, InputKind, InputOption, InputSection, WorkflowPlan

__all__ = [
    "EventStream",
    "OperationContext",
    "ApiCommandsResult",
    "ApiSchemaResult",
    "ApiSchemasResult",
    "ApiWorkflowResult",
    "ApplyActionResult",
    "ApplyCounts",
    "ApplyResult",
    "ClientDetail",
    "ClientHandoff",
    "ClientListResult",
    "ClientListServiceResult",
    "ClientListSummary",
    "ClientNotFoundError",
    "ClientPanelClient",
    "ClientRecord",
    "ClientShowResult",
    "ClientShowServiceResult",
    "CaptureReporter",
    "COMMAND_COMPLETED",
    "COMMAND_FAILED",
    "COMMAND_STARTED",
    "CommandSpec",
    "CoreModel",
    "CoreEventType",
    "DeployExecutor",
    "DeployClusterState",
    "DeployNodeState",
    "DeployPlan",
    "DeployPlanningError",
    "DeployPorts",
    "DeployRequest",
    "DeployResult",
    "DeployWorkflowAnswers",
    "ErrorCategory",
    "Event",
    "EventLevel",
    "FleetPanelClient",
    "FleetInventory",
    "FleetInventoryServiceResult",
    "FleetSources",
    "FleetStatus",
    "FleetStatusServiceResult",
    "FleetTopology",
    "InputField",
    "InputKind",
    "InputOption",
    "InputSection",
    "MeridianError",
    "NoopReporter",
    "OutputEnvelope",
    "OutputStatus",
    "PanelErrorClassifier",
    "PanelErrorKind",
    "PlanActionResult",
    "PlanCounts",
    "PlanResult",
    "PROVISION_STEP_COMPLETED",
    "PROVISION_STEP_FAILED",
    "PROVISION_STEP_STARTED",
    "REDACTED",
    "Reporter",
    "RemoteCommandResult",
    "RemoteExecutor",
    "RemoteTarget",
    "PutBytesSpec",
    "PutTextSpec",
    "RelayHealthChecker",
    "ResourceRef",
    "RelayHostRef",
    "ShareUrlBuilder",
    "Summary",
    "CommandCatalogEntry",
    "CommandContract",
    "CommandOutcome",
    "EmptyData",
    "SchemaCatalogEntry",
    "collect_client_list",
    "collect_client_show",
    "deploy_server",
    "command_envelope",
    "command_catalog",
    "command_contracts",
    "collect_fleet_inventory",
    "collect_fleet_status",
    "envelope",
    "emit_event",
    "json_dumps",
    "jsonl_dumps",
    "plan_payload",
    "redact",
    "build_plan_result",
    "build_apply_result",
    "apply_deploy_workflow_answers",
    "schema_catalog",
    "schema_for",
    "schema_names",
    "validate_command_envelope",
    "WorkflowPlan",
    "WorkflowNotFoundError",
    "build_deploy_workflow",
    "build_deploy_plan",
    "collect_workflow",
    "compute_deploy_ports",
]
