"""Meridian core API primitives.

Core modules expose typed request/result/event contracts used by CLI, future
UI clients, and automation adapters. They must not depend on Typer command
parsing or Rich console state.
"""

from meridian.core.clients import (
    ClientDetail,
    ClientHandoff,
    ClientListResult,
    ClientListSummary,
    ClientRecord,
    ClientShowResult,
)
from meridian.core.fleet import FleetInventory, FleetSources, FleetStatus, FleetTopology, RelayHostRef
from meridian.core.models import (
    CoreModel,
    ErrorCategory,
    Event,
    EventLevel,
    MeridianError,
    OutputEnvelope,
    OutputStatus,
    ResourceRef,
    Summary,
)
from meridian.core.output import (
    EventStream,
    OperationContext,
    command_envelope,
    envelope,
    json_dumps,
    jsonl_dumps,
    plan_payload,
)
from meridian.core.plan import PlanActionResult, PlanCounts, PlanResult, build_plan_result
from meridian.core.redaction import REDACTED, redact
from meridian.core.schema import (
    ApiCommandsResult,
    ApiSchemaResult,
    ApiSchemasResult,
    CommandCatalogEntry,
    CommandContract,
    CommandOutcome,
    EmptyData,
    SchemaCatalogEntry,
    command_catalog,
    command_contracts,
    schema_catalog,
    schema_for,
    schema_names,
    validate_command_envelope,
)
from meridian.core.services import (
    ClientListServiceResult,
    ClientNotFoundError,
    ClientPanelClient,
    ClientShowServiceResult,
    FleetInventoryServiceResult,
    FleetPanelClient,
    FleetStatusServiceResult,
    PanelErrorClassifier,
    PanelErrorKind,
    RelayHealthChecker,
    ShareUrlBuilder,
    collect_client_list,
    collect_client_show,
    collect_fleet_inventory,
    collect_fleet_status,
)

__all__ = [
    "EventStream",
    "OperationContext",
    "ApiCommandsResult",
    "ApiSchemaResult",
    "ApiSchemasResult",
    "ClientDetail",
    "ClientHandoff",
    "ClientListResult",
    "ClientListServiceResult",
    "ClientListSummary",
    "ClientNotFoundError",
    "ClientPanelClient",
    "ClientRecord",
    "ClientShowResult",
    "ClientShowServiceResult",
    "CoreModel",
    "ErrorCategory",
    "Event",
    "EventLevel",
    "FleetPanelClient",
    "FleetInventory",
    "FleetInventoryServiceResult",
    "FleetSources",
    "FleetStatus",
    "FleetStatusServiceResult",
    "FleetTopology",
    "MeridianError",
    "OutputEnvelope",
    "OutputStatus",
    "PanelErrorClassifier",
    "PanelErrorKind",
    "PlanActionResult",
    "PlanCounts",
    "PlanResult",
    "REDACTED",
    "RelayHealthChecker",
    "ResourceRef",
    "RelayHostRef",
    "ShareUrlBuilder",
    "Summary",
    "CommandCatalogEntry",
    "CommandContract",
    "CommandOutcome",
    "EmptyData",
    "SchemaCatalogEntry",
    "collect_client_list",
    "collect_client_show",
    "command_envelope",
    "command_catalog",
    "command_contracts",
    "collect_fleet_inventory",
    "collect_fleet_status",
    "envelope",
    "json_dumps",
    "jsonl_dumps",
    "plan_payload",
    "redact",
    "build_plan_result",
    "schema_catalog",
    "schema_for",
    "schema_names",
    "validate_command_envelope",
]
